#!/usr/bin/env python3
"""
MockCLI — a stand-in coding CLI used by the test suite.

It behaves like a headless coding CLI invoked as::

    python3 mock_cli.py [--model X] [--agent Y] [--effort Z] "<prompt>"

Behaviour is driven by environment variables so tests can simulate different
outcomes without a real CLI / network:

  MOCK_COST_MODE   kiro | claude | copilot | none   (default: kiro)
  MOCK_CREDITS     Kiro credits to report           (default: 0.05)
  MOCK_TIME_S      seconds to report                (default: 2)
  MOCK_USD         claude total_cost_usd            (default: 0.01)
  MOCK_WRITE_FILE  filename to create in cwd        (default: solution.py)
  MOCK_FILE_BODY   contents of that file            (default: a passing marker)
  MOCK_EXIT        process exit code                (default: 0)
  MOCK_EMIT        extra text to print to stdout    (default: "")
  MOCK_TRANSIENT   if "1", emit a transient backend error and exit nonzero
  MOCK_UNAVAILABLE if "1", emit the model-unavailable banner
  MOCK_NOOP        if "1", produce no file and no credits (no-op run)

It always prints a short banner so transcripts are non-empty.
"""

from __future__ import annotations

import json
import os
import sys


def main() -> int:
    args = sys.argv[1:]
    prompt = args[-1] if args else ""

    if os.environ.get("MOCK_UNAVAILABLE") == "1":
        print("The model you've selected is temporarily unavailable. Please relaunch with another model.")
        return 0

    if os.environ.get("MOCK_TRANSIENT") == "1":
        sys.stderr.write("error sending request for url (runtime.example.kiro.dev): dispatch failure\n")
        return 1

    # Simulate a hung CLI: print some output, then block. Used to test that the
    # harness captures partial output before killing on timeout.
    if os.environ.get("MOCK_HANG") == "1":
        import time
        print("PARTIAL_OUTPUT_BEFORE_HANG", flush=True)
        sys.stderr.write("starting work...\n")
        sys.stderr.flush()
        time.sleep(float(os.environ.get("MOCK_HANG_SECONDS", "30")))
        return 0

    noop = os.environ.get("MOCK_NOOP") == "1"

    if not noop:
        fname = os.environ.get("MOCK_WRITE_FILE", "solution.py")
        body = os.environ.get("MOCK_FILE_BODY", "# generated by MockCLI\nRESULT_OK = True\n")
        try:
            with open(fname, "w", encoding="utf-8") as f:
                f.write(body)
        except OSError:
            pass

    print(f"[MockCLI] handled prompt ({len(prompt)} chars)")
    extra = os.environ.get("MOCK_EMIT")
    if extra:
        print(extra)

    cost_mode = os.environ.get("MOCK_COST_MODE", "kiro")
    if not noop:
        if cost_mode == "kiro":
            credits = os.environ.get("MOCK_CREDITS", "0.05")
            time_s = os.environ.get("MOCK_TIME_S", "2")
            sys.stderr.write(f"\u25b8 Credits: {credits} \u2022 Time: {time_s}s\n")
        elif cost_mode == "claude":
            usd = float(os.environ.get("MOCK_USD", "0.01"))
            time_s = float(os.environ.get("MOCK_TIME_S", "2"))
            obj = {
                "type": "result",
                "total_cost_usd": usd,
                "duration_ms": int(time_s * 1000),
                "usage": {"input_tokens": 1000, "output_tokens": 200},
            }
            print(json.dumps(obj))
        elif cost_mode == "copilot":
            time_s = float(os.environ.get("MOCK_TIME_S", "2"))
            obj = {
                "type": "result",
                "sessionId": os.environ.get("MOCK_SESSION_ID", "mock-session"),
                "premiumRequests": float(os.environ.get("MOCK_PREMIUM", "0.33")),
                "sessionDurationMs": int(time_s * 1000),
                "usage": {"input_tokens": 1000, "output_tokens": 200},
            }
            print(json.dumps(obj))

    return int(os.environ.get("MOCK_EXIT", "0"))


if __name__ == "__main__":
    sys.exit(main())
